# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:24
from __future__ import unicode_literals

import datetimeutc.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('extract', django.contrib.postgres.fields.jsonb.JSONField()),
                ('summary', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('url', models.URLField(max_length=2048)),
                ('source_type', models.PositiveIntegerField(choices=[(1, 1), (2, 2)])),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Source'),
        ),
    ]
