# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubisherURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='source',
        ),
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.URLField(default=None, max_length=2048),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AddField(
            model_name='pubisherurl',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publisher'),
        ),
    ]
