# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 23:39
from __future__ import unicode_literals

import datetimeutc.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160407_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnteredSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('updated', models.DateTimeField(null=True)),
                ('url', models.URLField(max_length=2048)),
                ('source_type', models.PositiveIntegerField(choices=[(1, 1), (2, 2)])),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publisher')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='entered_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.EnteredSource'),
            preserve_default=False,
        ),
    ]
