# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160407_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PubisherURL',
            new_name='PublisherURL',
        ),
    ]
