# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:00
from __future__ import unicode_literals

import datetimeutc.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160408_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enteredsource',
            name='updated',
            field=datetimeutc.fields.DateTimeUTCField(null=True),
        ),
    ]
