# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160411_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enteredsource',
            old_name='updated',
            new_name='last_polled',
        ),
        migrations.AlterField(
            model_name='enteredsource',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Publisher'),
        ),
    ]
