# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160411_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='enteredsource',
            name='last_error',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
