# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enteredsource_last_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='guid',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='enteredsource',
            name='source_type',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
