# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160413_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enteredsource',
            name='publisher',
        ),
        migrations.AddField(
            model_name='content',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Publisher'),
        ),
    ]
