# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160413_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_topics', models.PositiveIntegerField(default=50)),
                ('lda_passes', models.SmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'LDA Configuration',
            },
        ),
    ]
