# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ldaconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
