# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:07
from __future__ import unicode_literals

import datetimeutc.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160426_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256, null=True)),
                ('timestamp', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('error_code', models.PositiveIntegerField()),
                ('object_type', models.CharField(max_length=256, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('summary', models.CharField(max_length=2048, null=True)),
                ('other', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enteredsource',
            name='source_type',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
