# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160512_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='error_code',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
