# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 00:43
from __future__ import unicode_literals

import core.models
import datetimeutc.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20160512_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=core.models.Workspace.get_default_title, max_length=256)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('created', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('edited', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='workspace',
            field=models.ManyToManyField(to='core.Workspace'),
        ),
    ]
