# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160604_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
