# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_workspace_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='workspace',
        ),
        migrations.AddField(
            model_name='workspace',
            name='articles',
            field=models.ManyToManyField(to='core.Content'),
        ),
    ]
