# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 20:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_content_pre_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
