# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-22 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20161122_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='articles',
        ),
    ]
