# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20161128_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacearticle',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
